#!/bin/bash

# 🚀 SPRINGBOOT QUICK START GUIDE

echo "╔═══════════════════════════════════════════════════════╗"
echo "║   Quản Lý Điểm Học Tập THCS - Spring Boot Version   ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# Check Java
echo "🔍 Kiểm tra Java..."
java -version 2>&1 | head -1

echo ""
echo "📁 Cấu trúc project:"
echo "  springboot-web/"
echo "  ├── src/main/java/com/quanlydiem/"
echo "  │   ├── models/"
echo "  │   ├── controllers/"
echo "  │   ├── services/"
echo "  │   └── repositories/"
echo "  ├── src/main/resources/"
echo "  │   ├── templates/index.html"
echo "  │   └── static/ (css, js)"
echo "  └── build.gradle"
echo ""

echo "🎯 QUICK COMMANDS:"
echo ""
echo "  1️⃣  Chạy ứng dụng:"
echo "      cd springboot-web"
echo "      ./run.sh"
echo ""
echo "  2️⃣  Build JAR:"
echo "      ./build.sh"
echo ""
echo "  3️⃣  Chạy với port khác:"
echo "      ./gradlew bootRun --args='--server.port=8081'"
echo ""
echo "  4️⃣  Deploy Railway:"
echo "      git push origin main"
echo "      (trên railway.app chọn deploy from GitHub)"
echo ""

echo "🌐 URLS:"
echo "  • Local: http://localhost:8080"
echo "  • Railway: https://quan-ly-diem-xxx.railway.app"
echo ""

echo "📊 API ENDPOINTS:"
echo "  GET    /api/hoc-sinh                 (list students)"
echo "  POST   /api/hoc-sinh                 (add student)"
echo "  GET    /api/diem                     (list scores)"
echo "  POST   /api/diem/hoc-sinh/{id}       (add score)"
echo "  GET    /api/hoc-sinh/stats/summary   (statistics)"
echo ""

echo "📚 DOCUMENTATION:"
echo "  • README.md - Hướng dẫn chi tiết"
echo "  • DEPLOYMENT_GUIDE.md - Deploy Railway"
echo "  • SPRINGBOOT_OVERVIEW.md - So sánh Desktop vs Web"
echo ""

echo "✨ FEATURES:"
echo "  ✅ Quản lý học sinh (CRUD)"
echo "  ✅ Quản lý điểm (CRUD)"
echo "  ✅ Tính DTB tự động"
echo "  ✅ Xếp loại học sinh"
echo "  ✅ Báo cáo & thống kê"
echo "  ✅ Giao diện web responsive"
echo "  ✅ REST API"
echo "  ✅ H2 Database"
echo ""

echo "🛠️  TECHNOLOGIES:"
echo "  • Java 17"
echo "  • Spring Boot 3.2.1"
echo "  • Spring Data JPA"
echo "  • H2 Database"
echo "  • HTML5/CSS3/JavaScript"
echo "  • Gradle"
echo ""

echo "⏱️  BUILD TIME:"
echo "  • First build: ~1-2 minutes"
echo "  • Next builds: ~10-20 seconds"
echo "  • Deploy Railway: 2-5 minutes"
echo ""

echo "🎓 OOP PRINCIPLES IMPLEMENTED:"
echo "  ✅ Inheritance (HocSinh extends ConNguoi)"
echo "  ✅ Polymorphism (IXepLoai interface)"
echo "  ✅ Encapsulation (services, repositories)"
echo "  ✅ Abstraction (JPA entities, interfaces)"
echo ""

echo "💡 TIPS:"
echo "  • Dùng Ctrl+C để stop server"
echo "  • Port default: 8080"
echo "  • Database: H2 (embedded, auto-created)"
echo "  • Free deploy: Railway (5$ credit/month)"
echo ""

echo "🚀 READY TO START!"
echo ""
echo "  cd springboot-web && ./run.sh"
echo ""
echo "Then open: http://localhost:8080"
echo ""
